# Generated by Django 3.0.3 on 2020-03-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookclub',
            name='Venu',
            field=models.CharField(choices=[('Gym', 'Gym'), ('Cardio Theater', 'Cardio Theater'), ('Personal Training Counter', 'Personal Training Counter'), ('Cardio Theater', 'Cardio Theater'), ('Cycling Studio', 'Cycling Studio'), ('Luxurious Changing Room', 'Luxurious Changing Room'), ('Members Lounge', 'Members Lounge'), ('restaurants', 'restaurants'), ('swimming pool', 'swimming pool')], max_length=25),
        ),
    ]
