# Generated by Django 3.0.3 on 2020-03-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0002_auto_20200306_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookclub',
            name='Occasion',
            field=models.CharField(choices=[('Birthday', 'Birthday'), ('Wedding', 'Wedding'), ('Marriage', 'Marriage'), ('Farewell', 'Farewell'), ('Marriage reception', 'Marriage reception'), ('Festival party', 'Festival party'), ('Other', 'Other')], max_length=25),
        ),
        migrations.AlterField(
            model_name='bookclub',
            name='Venu',
            field=models.CharField(choices=[('Gym', 'Gym'), ('Cardio Theater', 'Cardio Theater'), ('Personal Training Counter', 'Personal Training Counter'), ('Cardio Theater', 'Cardio Theater'), ('Cycling Studio', 'Cycling Studio'), ('Luxurious Changing Room', 'Luxurious Changing Room'), ('Members Lounge', 'Members Lounge'), ('restaurants', 'restaurants'), ('swimming pool', 'swimming pool'), ('Other', 'Other')], max_length=25),
        ),
    ]
