# Generated by Django 3.0.3 on 2020-03-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0003_auto_20200307_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookclub',
            name='Venu',
            field=models.CharField(choices=[('Gym | 2500', 'Gym'), ('Cardio Theater | 3000', 'Cardio Theater'), ('Personal Training Counter | 4000', 'Personal Training Counter'), ('Cycling Studio | 4000', 'Cycling Studio'), ('Luxurious Changing Room | 6000', 'Luxurious Changing Room'), ('Members Lounge | 5000', 'Members Lounge'), ('restaurants | 7000', 'restaurants'), ('swimming pool | 3000', 'swimming pool')], max_length=100),
        ),
    ]
