# Generated by Django 3.0.3 on 2020-03-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0005_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookclub',
            name='Occasion',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='bookclub',
            name='Venu',
            field=models.CharField(max_length=100),
        ),
    ]
