# Generated by Django 3.0.3 on 2020-03-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0006_auto_20200324_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookclub',
            name='Price',
            field=models.CharField(default=12, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookclub',
            name='person',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
