# Generated by Django 3.0.3 on 2020-03-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0007_auto_20200324_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookclub',
            name='Price',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bookclub',
            name='person',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
