# Generated by Django 3.0.3 on 2020-03-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0008_auto_20200324_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Occasion', models.CharField(max_length=10)),
                ('Bio', models.TextField()),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
            ],
        ),
    ]
